# Custom Language File for Launcher Customizer

[ejs.app]
title = "NFG Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.networkforgamers.com"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Welcome To Network For Gamers"
welcomeDescription = "We are a gaming community welcoming everyone. We use our discord as a central place for our company and community. We hope you enjoy your stay and make it a long one. We offer many services such as: Server hosting, game & web hosting, Minecraft Modpacks, Minecraft Resource Packs, and free discord bots."
welcomeDescCTA = "You are just a few clicks away from NFGMC"
